
INSERT INTO properties (
    title, price, pricePerSquareMeter, address, layout, area, floorInfo,
    structure, managementFee, areaOfUse, transportation, location, propertyType,
    yearBuilt, balconyArea, totalUnits, repairReserveFund, landLeaseFee,
    rightFee, depositGuarantee, maintenanceFees, otherFees, bicycleParking,
    bikeStorage, siteArea, pets, landRights, managementForm, landLawNotification,
    currentSituation, extraditionPossibleDate, transactionMode, propertyNumber,
    informationReleaseDate, nextScheduledUpdateDate, remarks, evaluationCertificate,
    parking, kitchen, bathToilet, facilitiesServices, others, images,
    zipcode, area_level_1, area_level_2, area_level_3, area_level_4, status
)
VALUES (
    'Unknown Property',
    4200,
    53,
    '神奈川県横浜市鶴見区東寺尾中台 GoogleMaps',
    '3LDK',
    79.6924,
    '2階 / 地上5階建',
    '鉄筋コンクリート造',
    9200,
    'NULL',
    '京浜東北・根岸線 鶴見駅 徒歩13分京急本線 京急鶴見駅 徒歩16分',
    NULL,
    '中古マンション',
    '2004年12月築',
    NULL,
    51,
    24400,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '有',
    '有',
    NULL,
    NULL,
    '所有権',
    '管理会社に全部委託',
    '届出不要',
    '空家',
    '相談',
    '仲介',
    F84AFA0B,
    '2025-06-16',
    '2025-06-30',
    '-',
    NULL,
    '空き無',
    'NULL',
    'NULL',
    'NULL',
    '-',
    ARRAY['/images/id75-1.jpg','/images/id75-2.jpg','/images/id75-3.jpg','/images/id75-4.jpg','/images/id75-5.jpg'],
    'NULL',
    '首都圏',
    '神奈川県',
    '横浜市',
    '鶴見',
    'for sale'
);
