-- Sample property data
INSERT INTO properties (
    title, price, pricePerSquareMeter, address, layout, area, floorInfo, 
    structure, managementFee, areaOfUse, transportation, location, propertyType, 
    yearBuilt, balconyArea, totalUnits, repairReserveFund, landLeaseFee, 
    rightFee, depositGuarantee, maintenanceFees, otherFees, bicycleParking, 
    bikeStorage, siteArea, pets, landRights, managementForm, landLawNotification, 
    currentSituation, extraditionPossibleDate, transactionMode, propertyNumber, 
    informationReleaseDate, nextScheduledUpdateDate, remarks, evaluationCertificate, 
    parking, kitchen, bathToilet, facilitiesServices, others, images
)
VALUES (
    '品川Vタワー', 
    184800000, 
    3401100, 
    '東京都港区港南２丁目', 
    '2LDK', 
    61.21, 
    '9/43階', 
    'RC', 
    20100, 
    '準工業地域', 
    '東京地下鉄南北線 「白金高輪」駅 まで 徒歩3分 東京都三田線 「白金高輪」駅 まで 徒歩3分', 
    ST_SetSRID(ST_MakePoint(139.74096167715788,35.625384789934486), 4326), -- Single Point: [lng, lat]
    '中古マンション', 
    '2003年3月', 
    4.57, 
    650, 
    16340, 
    1320, 
    NULL, 
    NULL, 
    'インターネット接続料: 2,200円/月、自治会費: 150円/月', 
    NULL, 
    '有', 
    '有', 
    NULL, 
    'ペット可', 
    '所有権', 
    '全部委託／日勤', 
    '届出不要', 
    '空家', 
    '相談', 
    '専任媒介', 
    1015229195, 
    '2025-05-30', 
    '2025-06-06', 
    '主要採光面：北向き', 
    'インターネット料、自治会費、HARUMI FLAG CLUB会費', 
    '空無', 
    'カウンターキッチン', 
    '-', 
    'オール電化／電気温水器', 
    '・インターネット使用料は2025年4月分より1，265円になります。', 
    ARRAY['/images/id10-1.jpg', '/images/id10-2.jpg', '/images/id10-3.jpg', '/images/id10-4.jpg', '/images/id10-5.jpg']
);