-- Sample property data
INSERT INTO properties (
    title, price, pricePerSquareMeter, address, layout, area, floorInfo, 
    structure, managementFee, areaOfUse, transportation, location, propertyType, 
    yearBuilt, balconyArea, totalUnits, repairReserveFund, landLeaseFee, 
    rightFee, depositGuarantee, maintenanceFees, otherFees, bicycleParking, 
    bikeStorage, siteArea, pets, landRights, managementForm, landLawNotification, 
    currentSituation, extraditionPossibleDate, transactionMode, propertyNumber, 
    informationReleaseDate, nextScheduledUpdateDate, remarks, evaluationCertificate, 
    parking, kitchen, bathToilet, facilitiesServices, others, images
)
VALUES (
    '東建ニューハイツ西新宿', 
    148000000, 
    3401100, 
    '東京都新宿区西新宿４丁目', 
    '4LDK', 
    104.38, 
    '12/12階', 
    'RC', 
    31460, 
    '準工業地域', 
    '東京都大江戸線 「西新宿五丁目」駅 まで 徒歩4分 東京地下鉄丸ノ内線 「西新宿」駅 まで 徒歩10分', 
    ST_SetSRID(ST_MakePoint(139.6875632790081,35.69080063336431), 4326), -- Single Point: [lng, lat]
    '中古マンション', 
    '1981年2月', 
    8.37, 
    157, 
    17310, 
    300, 
    NULL, 
    NULL, 
    'インターネット接続料: 2,200円/月、自治会費: 150円/月', 
    NULL, 
    '有', 
    '有', 
    NULL, 
    'ペット不可', 
    '所有権', 
    '全部委託／日勤', 
    '届出不要', 
    '賃貸中', 
    '相談', 
    '専任媒介', 
    1015229195, 
    '2025-05-30', 
    '2025-06-06', 
    '主要採光面：北向き', 
    'インターネット料、自治会費、HARUMI FLAG CLUB会費', 
    '空無', 
    'カウンターキッチン', 
    '-', 
    'オール電化／電気温水器', 
    '駐車場等の空き状況につきましては、随時ご確認ください。月額賃料等388 000円にて賃貸中 普通借家契約　 契約期間：2023/7/15～2025/7/14', 
    ARRAY['/images/id12-1.jpg', '/images/id12-2.jpg', '/images/id12-3.jpg', '/images/id12-4.jpg', '/images/id12-5.jpg']
);