-- Sample property data
INSERT INTO properties (
    title, price, pricePerSquareMeter, address, layout, area, floorInfo, 
    structure, managementFee, areaOfUse, transportation, location, propertyType, 
    yearBuilt, balconyArea, totalUnits, repairReserveFund, landLeaseFee, 
    rightFee, depositGuarantee, maintenanceFees, otherFees, bicycleParking, 
    bikeStorage, siteArea, pets, landRights, managementForm, landLawNotification, 
    currentSituation, extraditionPossibleDate, transactionMode, propertyNumber, 
    informationReleaseDate, nextScheduledUpdateDate, remarks, evaluationCertificate, 
    parking, kitchen, bathToilet, facilitiesServices, others, images
)
VALUES (
    'シエン・コンドミニオ', 
    41800000, 
    3401100, 
    '東京都新宿区百人町２丁目', 
    '1K', 
    32.44, 
    '1/6階', 
    'RC', 
    9100, 
    '準工業地域', 
    '総武・中央緩行線 「大久保」駅 まで 徒歩5分 山手線 「新大久保」駅 まで 徒歩7分', 
    ST_SetSRID(ST_MakePoint(139.6976880292879, 35.70427784217023), 4326), -- Single Point: [lng, lat]
    '中古マンション', 
    '2000年11月', 
    12.07, 
    74, 
    7620, 
    NULL, 
    NULL, 
    NULL, 
    'インターネット接続料: 2,200円/月、自治会費: 150円/月', 
    NULL, 
    '有', 
    '有', 
    NULL, 
    'ペット可', 
    '所有権', 
    '全部委託／日勤', 
    '届出不要', 
    '空家', 
    '相談', 
    '専任媒介', 
    1015229195, 
    '2025-05-30', 
    '2025-06-06', 
    '主要採光面：北向き', 
    'インターネット料、自治会費、HARUMI FLAG CLUB会費', 
    '空無', 
    'カウンターキッチン', 
    '-', 
    'オール電化／電気温水器', 
    '■水回り：2025年2月,キッチン、浴室、トイレ、洗面所、給湯器,■内装：2025年2月, 全面(床・壁・天井・建具)', 
    ARRAY['/images/id13-1.jpg', '/images/id13-2.jpg', '/images/id13-3.jpg', '/images/id13-4.jpg', '/images/id13-5.jpg']
);