-- Sample property data
INSERT INTO properties (
    title, price, pricePerSquareMeter, address, layout, area, floorInfo, 
    structure, managementFee, areaOfUse, transportation, location, propertyType, 
    yearBuilt, balconyArea, totalUnits, repairReserveFund, landLeaseFee, 
    rightFee, depositGuarantee, maintenanceFees, otherFees, bicycleParking, 
    bikeStorage, siteArea, pets, landRights, managementForm, landLawNotification, 
    currentSituation, extraditionPossibleDate, transactionMode, propertyNumber, 
    informationReleaseDate, nextScheduledUpdateDate, remarks, evaluationCertificate, 
    parking, kitchen, bathToilet, facilitiesServices, others, images
)
VALUES (
    'アールヴェール文京大塚公園', 
    139000000, 
    3401100, 
    '東京都文京区大塚５丁目', 
    '3LDK', 
    73.58, 
    '7/14階', 
    'RC', 
    12070, 
    '準工業地域', 
    '総武・中央緩行線 「大久保」駅 まで 徒歩5分 山手線 「新大久保」駅 まで 徒歩7分', 
    ST_SetSRID(ST_MakePoint(139.73136807290675,35.72393586454848), 4326), -- Single Point: [lng, lat]
    '中古マンション', 
    '1999年12月', 
    11.07, 
    79, 
    24060, 
    NULL, 
    NULL, 
    NULL, 
    'インターネット接続料: 2,200円/月、自治会費: 150円/月', 
    NULL, 
    '有', 
    '有', 
    NULL, 
    'ペット可', 
    '所有権', 
    '全部委託／日勤', 
    '届出不要', 
    '居住中', 
    '相談', 
    '専任媒介', 
    1015229195, 
    '2025-05-30', 
    '2025-06-06', 
    '主要採光面：北向き', 
    'インターネット料、自治会費、HARUMI FLAG CLUB会費', 
    '空無', 
    'カウンターキッチン', 
    '-', 
    'オール電化／電気温水器', 
    '■水回り：2025年2月,キッチン、浴室、トイレ、洗面所、給湯器,■内装：2025年2月, 全面(床・壁・天井・建具)', 
    ARRAY['/images/id14-1.jpg', '/images/id14-2.jpg', '/images/id14-3.jpg', '/images/id14-4.jpg', '/images/id14-5.jpg']
);