-- Sample property data
INSERT INTO properties (
    title, price, pricePerSquareMeter, address, layout, area, floorInfo, 
    structure, managementFee, areaOfUse, transportation, location, propertyType, 
    yearBuilt, balconyArea, totalUnits, repairReserveFund, landLeaseFee, 
    rightFee, depositGuarantee, maintenanceFees, otherFees, bicycleParking, 
    bikeStorage, siteArea, pets, landRights, managementForm, landLawNotification, 
    currentSituation, extraditionPossibleDate, transactionMode, propertyNumber, 
    informationReleaseDate, nextScheduledUpdateDate, remarks, evaluationCertificate, 
    parking, kitchen, bathToilet, facilitiesServices, others, images
)
VALUES (
    'アールヴェール文京白山', 
    119800000, 
    3401100, 
    '東京都文京区本駒込１丁目', 
    '3LDK', 
    80.16, 
    '7/15階', 
    'RC', 
    16100, 
    '準工業地域', 
    '東京地下鉄南北線 「本駒込」駅 まで 徒歩1分 東京都三田線 「白山」駅 まで 徒歩5分', 
    ST_SetSRID(ST_MakePoint(139.75424162318618,35.72354043648502), 4326), -- Single Point: [lng, lat]
    '中古マンション', 
    '1999年10月', 
    9.09, 
    85, 
    27180, 
    NULL, 
    NULL, 
    NULL, 
    'インターネット接続料: 2,200円/月、自治会費: 150円/月', 
    NULL, 
    '有', 
    '有', 
    NULL, 
    'ペット不可', 
    '所有権', 
    '全部委託／日勤', 
    '届出不要', 
    '居住中', 
    '相談', 
    '専任媒介', 
    1015229195, 
    '2025-05-30', 
    '2025-06-06', 
    '主要採光面：北向き', 
    '', 
    '空無', 
    'カウンターキッチン', 
    '-', 
    'オール電化／電気温水器', 
    '■水回り：2025年2月,キッチン、浴室、トイレ、洗面所、給湯器,■内装：2025年2月, 全面(床・壁・天井・建具)', 
    ARRAY['/images/id15-1.jpg', '/images/id15-2.jpg', '/images/id15-3.jpg', '/images/id15-4.jpg', '/images/id15-5.jpg']
);