INSERT INTO properties (
    title, price, pricePerSquareMeter, address, layout, area, floorInfo,
    structure, managementFee, areaOfUse, transportation, location, propertyType,
    yearBuilt, balconyArea, totalUnits, repairReserveFund, landLeaseFee,
    rightFee, depositGuarantee, maintenanceFees, otherFees, bicycleParking,
    bikeStorage, siteArea, pets, landRights, managementForm, landLawNotification,
    currentSituation, extraditionPossibleDate, transactionMode, propertyNumber,
    informationReleaseDate, nextScheduledUpdateDate, remarks, evaluationCertificate,
    parking, kitchen, bathToilet, facilitiesServices, others, images
)
VALUES (
    'ランドステージ錦糸町２',
    199900000,
    2547436,
    '東京都墨田区太平4丁目1番1号',
    '2LDK',
    78.5,
    '地上45階地下2階建 / 29階',
    'RC',
    45600,
    '準工業地域',
    '東京メトロ半蔵門線 / 錦糸町駅 徒歩4分',
    ST_SetSRID(ST_MakePoint(139.8070975692615, 35.69448708237164), 4326),
    '中古マンション',
    '2006年2月',
    6.43,
    644,
    32500,
    28900,
    NULL,
    NULL,
    '管理費込み、修繕積立金: 28900円/月',
    NULL,
    '有',
    '有',
    NULL,
    '相談',
    '所有権',
    '全部委託／日勤',
    '届出不要',
    '空家',
    '相談',
    '専任媒介',
    1015229196,
    '2025-05-29',
    '2025-06-29',
    '高層階、錦糸公園眺望、オリナス直結',
    NULL,
    '有',
    'システムキッチン',
    'バス・トイレ別',
    'オートロック、宅配ボックス、エレベーター、フロントサービス',
    '24時間警備、ゲストルーム、フィットネス、スカイラウンジ',
    ARRAY['/images/id16-1.jpg', '/images/id16-2.jpg', '/images/id16-3.jpg', '/images/id16-4.jpg', '/images/id16-5.jpg']
);