INSERT INTO properties (
    title, price, pricePerSquareMeter, address, layout, area, floorInfo,
    structure, managementFee, areaOfUse, transportation, location, propertyType,
    yearBuilt, balconyArea, totalUnits, repairReserveFund, landLeaseFee,
    rightFee, depositGuarantee, maintenanceFees, otherFees, bicycleParking,
    bikeStorage, siteArea, pets, landRights, managementForm, landLawNotification,
    currentSituation, extraditionPossibleDate, transactionMode, propertyNumber,
    informationReleaseDate, nextScheduledUpdateDate, remarks, evaluationCertificate,
    parking, kitchen, bathToilet, facilitiesServices, others, images
)
VALUES (
    'センチュリーパークタワー 15階 3LDK',
    450000000,
    3891304,
    '東京都中央区佃2丁目1番2号',
    '3LDK',
    115.7,
    '地上54階地下3階建 / 15階',
    'SRC',
    68200,
    '準工業地域',
    '東京メトロ有楽町線 / 月島駅 徒歩8分',
    ST_SetSRID(ST_MakePoint(139.7850, 35.6701), 4326),
    '中古マンション',
    '1999年1月',
    12.5,
    756,
    80880,
    85670,
    NULL,
    NULL,
    'インターネット接続料: 2200円/月、自治会費: 150円/月',
    NULL,
    '有',
    '有',
    NULL,
    '相談',
    '所有権',
    '全部委託／日勤',
    '届出不要',
    '空家',
    '相談',
    '専任媒介',
    1015229197,
    '2025-05-29',
    '2025-06-29',
    '東京湾眺望、タワーマンション、リバーサイド',
    NULL,
    '有',
    'アイランドキッチン',
    'バス・トイレ別',
    'コンシェルジュ、ゲストルーム、ライブラリー、スポーツジム',
    '24時間有人管理、宅配ロッカー、ペット足洗い場',
    ARRAY['/images/id17-1.jpg', '/images/id17-2.jpg', '/images/id17-3.jpg', '/images/id17-4.jpg', '/images/id17-5.jpg']
);