INSERT INTO properties (
    title, price, pricePerSquareMeter, address, layout, area, floorInfo,
    structure, managementFee, areaOfUse, transportation, location, propertyType,
    yearBuilt, balconyArea, totalUnits, repairReserveFund, landLeaseFee,
    rightFee, depositGuarantee, maintenanceFees, otherFees, bicycleParking,
    bikeStorage, siteArea, pets, landRights, managementForm, landLawNotification,
    currentSituation, extraditionPossibleDate, transactionMode, propertyNumber,
    informationReleaseDate, nextScheduledUpdateDate, remarks, evaluationCertificate,
    parking, kitchen, bathToilet, facilitiesServices, others, images
)
VALUES (
    'グランドタワー品川 8階 1LDK',
    72000000,
    1440000,
    '東京都品川区上大崎2丁目25番2号',
    '1LDK',
    50.0,
    '地上42階地下2階建 / 8階',
    'RC',
    22800,
    '商業地域',
    'JR山手線 / 目黒駅 徒歩3分',
    ST_SetSRID(ST_MakePoint(139.7157, 35.6339), 4326),
    '中古マンション',
    '2015年9月',
    8.2,
    428,
    35600,
    28400,
    NULL,
    NULL,
    '管理費込み、修繕積立金別途',
    NULL,
    '有',
    '有',
    NULL,
    '不可',
    '所有権',
    '全部委託／日勤',
    '届出不要',
    '居住中',
    '相談',
    '専任媒介',
    1015229199,
    '2025-05-29',
    '2025-06-29',
    '駅近、コンパクト、投資用',
    NULL,
    '有',
    'システムキッチン',
    'ユニットバス',
    'オートロック、宅配ボックス、エレベーター',
    '管理人日勤、防犯カメラ',
    ARRAY['/images/id19-1.jpg', '/images/id19-2.jpg', '/images/id19-3.jpg', '/images/id19-4.jpg', '/images/id19-5.jpg']
);