-- Sample property data
INSERT INTO properties (
    title, price, pricePerSquareMeter, address, layout, area, floorInfo, 
    structure, managementFee, areaOfUse, transportation, location, propertyType, 
    yearBuilt, balconyArea, totalUnits, repairReserveFund, landLeaseFee, 
    rightFee, depositGuarantee, maintenanceFees, otherFees, bicycleParking, 
    bikeStorage, siteArea, pets, landRights, managementForm, landLawNotification, 
    currentSituation, extraditionPossibleDate, transactionMode, propertyNumber, 
    informationReleaseDate, nextScheduledUpdateDate, remarks, evaluationCertificate, 
    parking, kitchen, bathToilet, facilitiesServices, others, images
)
VALUES (
    'センチュリーパークタワー 50階 ４ＬＤＫ', 
    598000000, 
    3401100, 
    '東京都中央区佃２丁目', 
    '4LDK', 
    175.83, 
    '地上54階地下3階建 / 50階', 
    'RC', 
    60700, 
    '準工業地域', 
    '東京メトロ有楽町線 / 月島駅 徒歩9分 東京メトロ有楽町線 / 月島駅 徒歩9分', 
    ST_SetSRID(ST_MakePoint(139.7850, 35.6701), 4326), -- Single Point: [lng, lat]
    '中古マンション', 
    '1999年1月', 
    8.40, 
    756, 
    80880, 
    81670, 
    NULL, 
    NULL, 
    'インターネット接続料: 2,200円/月、自治会費: 150円/月', 
    NULL, 
    '有', 
    '有', 
    NULL, 
    '相談', 
    '所有権', 
    '全部委託／日勤', 
    '届出不要', 
    '空家', 
    '相談', 
    '専任媒介', 
    1015229195, 
    '2025-04-26', 
    '2025-06-10', 
    '主要採光面：北向き, 施工会社：（株）大林組, 用途地域：準工業', 
    '長期優良住宅認定通知書, 長期優良住宅認定通知書あり', 
    '空無', 
    'カウンターキッチン', 
    '-', 
    '全居室収納、ウォークインクローゼット、床暖房、トランクルーム、オートロック、モニター付インターホン、ディンプルキー、防犯カメラ、都市ガス、ケーブルTV', 
    '主要採光面：南向き,用途地域：商業地域,駐車場空状況：2025年4月確認リフォーム：(室内フルリフォーム中(2025年5月上旬完成予定))管理形態：全部委託／・熱料金：変動費（使用相当分の料金が別途かかります）', 
    ARRAY['/images/id2-1.jpg', '/images/id2-2.jpg', '/images/id2-3.jpg', '/images/id2-4.jpg', '/images/id2-5.jpg']
);