INSERT INTO properties (
    title, price, pricePerSquareMeter, address, layout, area, floorInfo,
    structure, managementFee, areaOfUse, transportation, location, propertyType,
    yearBuilt, balconyArea, totalUnits, repairReserveFund, landLeaseFee,
    rightFee, depositGuarantee, maintenanceFees, otherFees, bicycleParking,
    bikeStorage, siteArea, pets, landRights, managementForm, landLawNotification,
    currentSituation, extraditionPossibleDate, transactionMode, propertyNumber,
    informationReleaseDate, nextScheduledUpdateDate, remarks, evaluationCertificate,
    parking, kitchen, bathToilet, facilitiesServices, others, images
)
VALUES (
    'ザ・パークハウス新宿 35階 2SLDK',
    380000000,
    4863248,
    '東京都新宿区西新宿4丁目15番3号',
    '2SLDK',
    78.1,
    '地上52階地下2階建 / 35階',
    'SRC',
    58900,
    '商業地域',
    '都営大江戸線 / 西新宿五丁目駅 徒歩4分',
    ST_SetSRID(ST_MakePoint(139.6917, 35.6895), 4326),
    '中古マンション',
    '2020年7月',
    14.3,
    895,
    67800,
    45200,
    NULL,
    NULL,
    '管理費込み、光熱費一部込み',
    NULL,
    '有',
    '有',
    NULL,
    '相談',
    '所有権',
    '全部委託／日勤',
    '届出不要',
    '空家',
    '相談',
    '専任媒介',
    1015229200,
    '2025-05-29',
    '2025-06-29',
    '新宿高層階、夜景眺望、最新設備',
    NULL,
    '有',
    'アイランドキッチン',
    'バス・トイレ別',
    'スカイラウンジ、フィットネス、ゲストルーム、コンシェルジュ',
    '24時間セキュリティ、宅配ロッカー、クリーニング取次',
    ARRAY['/images/id20-1.jpg', '/images/id20-2.jpg', '/images/id20-3.jpg', '/images/id20-4.jpg', '/images/id20-5.jpg']
);