INSERT INTO properties (
    title, price, pricePerSquareMeter, address, layout, area, floorInfo,
    structure, managementFee, areaOfUse, transportation, location, propertyType,
    yearBuilt, balconyArea, totalUnits, repairReserveFund, landLeaseFee,
    rightFee, depositGuarantee, maintenanceFees, otherFees, bicycleParking,
    bikeStorage, siteArea, pets, landRights, managementForm, landLawNotification,
    currentSituation, extraditionPossibleDate, transactionMode, propertyNumber,
    informationReleaseDate, nextScheduledUpdateDate, remarks, evaluationCertificate,
    parking, kitchen, bathToilet, facilitiesServices, others, images
)
VALUES (
    'プラウドタワー渋谷 18階 3LDK',
    295000000,
    3289474,
    '東京都渋谷区恵比寿4丁目20番3号',
    '3LDK',
    89.7,
    '地上39階建 / 18階',
    'RC',
    48600,
    '商業地域',
    'JR山手線 / 恵比寿駅 徒歩6分',
    ST_SetSRID(ST_MakePoint(139.7109, 35.6467), 4326),
    '中古マンション',
    '2017年11月',
    11.8,
    512,
    52400,
    38900,
    NULL,
    NULL,
    '管理費込み、修繕積立金別途',
    NULL,
    '有',
    '有',
    NULL,
    '可',
    '所有権',
    '全部委託／日勤',
    '届出不要',
    '空家',
    '即時',
    '専任媒介',
    1015229201,
    '2025-05-29',
    '2025-06-29',
    '恵比寿駅近、南向き、リノベーション済み',
    NULL,
    '有',
    'カウンターキッチン',
    'バス・トイレ別',
    'ラウンジ、ゲストルーム、キッズルーム、宅配ボックス',
    'コンシェルジュ、24時間管理、クリーニング取次',
    ARRAY['/images/id21-1.jpg', '/images/id21-2.jpg', '/images/id21-3.jpg', '/images/id21-4.jpg', '/images/id21-5.jpg']
);
