INSERT INTO properties (
    title, price, pricePerSquareMeter, address, layout, area, floorInfo,
    structure, managementFee, areaOfUse, transportation, location, propertyType,
    yearBuilt, balconyArea, totalUnits, repairReserveFund, landLeaseFee,
    rightFee, depositGuarantee, maintenanceFees, otherFees, bicycleParking,
    bikeStorage, siteArea, pets, landRights, managementForm, landLawNotification,
    currentSituation, extraditionPossibleDate, transactionMode, propertyNumber,
    informationReleaseDate, nextScheduledUpdateDate, remarks, evaluationCertificate,
    parking, kitchen, bathToilet, facilitiesServices, others, images
)
VALUES (
    'パークシティ中央湊 12階 2LDK',
    168000000,
    2133333,
    '東京都中央区湊1丁目5番2号',
    '2LDK',
    78.8,
    '地上32階建 / 12階',
    'RC',
    35200,
    '商業地域',
    '東京メトロ日比谷線 / 八丁堀駅 徒歩5分',
    ST_SetSRID(ST_MakePoint(139.7811, 35.6706), 4326),
    '中古マンション',
    '2019年3月',
    9.4,
    285,
    42800,
    31500,
    NULL,
    NULL,
    '管理費込み、インターネット使用料込み',
    NULL,
    '有',
    '有',
    NULL,
    '不可',
    '所有権',
    '全部委託／日勤',
    '届出不要',
    '居住中',
    '2025年8月',
    '専任媒介',
    1015229202,
    '2025-05-29',
    '2025-06-29',
    '東京駅徒歩圏、水辺立地、モダン設計',
    NULL,
    '有',
    'システムキッチン',
    'バス・トイレ別',
    'ラウンジ、フィットネス、ゲストルーム、宅配ボックス',
    '24時間管理、コンシェルジュ、クリーニング取次',
    ARRAY['/images/id22-1.jpg', '/images/id22-2.jpg', '/images/id22-3.jpg', '/images/id22-4.jpg', '/images/id22-5.jpg']
);