INSERT INTO properties (
    title, price, pricePerSquareMeter, address, layout, area, floorInfo,
    structure, managementFee, areaOfUse, transportation, location, propertyType,
    yearBuilt, balconyArea, totalUnits, repairReserveFund, landLeaseFee,
    rightFee, depositGuarantee, maintenanceFees, otherFees, bicycleParking,
    bikeStorage, siteArea, pets, landRights, managementForm, landLawNotification,
    currentSituation, extraditionPossibleDate, transactionMode, propertyNumber,
    informationReleaseDate, nextScheduledUpdateDate, remarks, evaluationCertificate,
    parking, kitchen, bathToilet, facilitiesServices, others, images
)
VALUES (
    'ザ・千代田麹町 25階 1SLDK',
    145000000,
    2535965,
    '東京都千代田区麹町3丁目5番2号',
    '1SLDK',
    57.2,
    '地上36階建 / 25階',
    'SRC',
    28900,
    '商業地域',
    '東京メトロ有楽町線 / 麹町駅 徒歩2分',
    ST_SetSRID(ST_MakePoint(139.7387, 35.6824), 4326),
    '中古マンション',
    '2021年4月',
    7.3,
    198,
    35600,
    25800,
    NULL,
    NULL,
    '管理費込み、修繕積立金別途',
    NULL,
    '有',
    '有',
    NULL,
    '不可',
    '所有権',
    '全部委託／日勤',
    '届出不要',
    '空家',
    '相談',
    '専任媒介',
    1015229203,
    '2025-05-29',
    '2025-06-29',
    '千代田区、高層階、皇居眺望',
    NULL,
    '有',
    'カウンターキッチン',
    'バス・トイレ別',
    'スカイラウンジ、ゲストルーム、宅配ボックス、ジム',
    'コンシェルジュ、24時間セキュリティ、ハウスキーピング',
    ARRAY['/images/id23-1.jpg', '/images/id23-2.jpg', '/images/id23-3.jpg', '/images/id23-4.jpg', '/images/id23-5.jpg']
);