INSERT INTO properties (
    title, price, pricePerSquareMeter, address, layout, area, floorInfo,
    structure, managementFee, areaOfUse, transportation, location, propertyType,
    yearBuilt, balconyArea, totalUnits, repairReserveFund, landLeaseFee,
    rightFee, depositGuarantee, maintenanceFees, otherFees, bicycleParking,
    bikeStorage, siteArea, pets, landRights, managementForm, landLawNotification,
    currentSituation, extraditionPossibleDate, transactionMode, propertyNumber,
    informationReleaseDate, nextScheduledUpdateDate, remarks, evaluationCertificate,
    parking, kitchen, bathToilet, facilitiesServices, others, images
)
VALUES (
    'グランドメゾン白金台 6階 4LDK',
    520000000,
    3734335,
    '東京都港区白金台4丁目10番8号',
    '4LDK',
    139.3,
    '地上21階建 / 6階',
    'RC',
    72500,
    '第一種住居地域',
    '東京メトロ南北線 / 白金台駅 徒歩3分',
    ST_SetSRID(ST_MakePoint(139.7286, 35.6424), 4326),
    '中古マンション',
    '2016年2月',
    16.2,
    89,
    58200,
    48900,
    NULL,
    NULL,
    '管理費込み、修繕積立金別途',
    NULL,
    '有',
    '有',
    NULL,
    '可',
    '所有権',
    '全部委託／日勤',
    '届出不要',
    '空家',
    '相談',
    '専任媒介',
    1015229204,
    '2025-05-29',
    '2025-06-29',
    '白金台低層高級、ファミリー向け、庭園眺望',
    NULL,
    '有',
    'アイランドキッチン',
    'バス・トイレ別',
    'ゲストルーム、ライブラリー、宅配ボックス、庭園',
    'コンシェルジュ、24時間管理、ハウスキーピング',
    ARRAY['/images/id24-1.jpg', '/images/id24-2.jpg', '/images/id24-3.jpg', '/images/id24-4.jpg', '/images/id24-5.jpg']
);
