INSERT INTO properties (
    title, price, pricePerSquareMeter, address, layout, area, floorInfo,
    structure, managementFee, areaOfUse, transportation, location, propertyType,
    yearBuilt, balconyArea, totalUnits, repairReserveFund, landLeaseFee,
    rightFee, depositGuarantee, maintenanceFees, otherFees, bicycleParking,
    bikeStorage, siteArea, pets, landRights, managementForm, landLawNotification,
    currentSituation, extraditionPossibleDate, transactionMode, propertyNumber,
    informationReleaseDate, nextScheduledUpdateDate, remarks, evaluationCertificate,
    parking, kitchen, bathToilet, facilitiesServices, others, images
)
VALUES (
    'ブリリア辰巳キャナルテラス 14階 3LDK',
    285000000,
    3356824,
    '東京都江東区辰巳2丁目1番58号',
    '3LDK',
    84.9,
    '地上33階建 / 14階',
    'RC',
    45800,
    '準工業地域',
    '東京メトロ有楽町線 / 辰巳駅 徒歩7分',
    ST_SetSRID(ST_MakePoint(139.8056, 35.6561), 4326),
    '中古マンション',
    '2018年8月',
    12.4,
    432,
    38900,
    32400,
    NULL,
    NULL,
    '管理費込み、修繕積立金別途',
    NULL,
    '有',
    '有',
    NULL,
    '相談',
    '所有権',
    '全部委託／日勤',
    '届出不要',
    '居住中',
    '2025年9月',
    '専任媒介',
    1015229205,
    '2025-05-29',
    '2025-06-29',
    '運河沿い、水辺眺望、子育て環境良好',
    NULL,
    '有',
    'システムキッチン',
    'バス・トイレ別',
    'キッズルーム、ゲストルーム、宅配ボックス、駐車場',
    '24時間管理、コンシェルジュ、防犯カメラ',
    ARRAY['/images/id25-1.jpg', '/images/id25-2.jpg', '/images/id25-3.jpg', '/images/id25-4.jpg', '/images/id25-5.jpg']
);