INSERT INTO properties (
    title, price, pricePerSquareMeter, address, layout, area, floorInfo,
    structure, managementFee, areaOfUse, transportation, location, propertyType,
    yearBuilt, balconyArea, totalUnits, repairReserveFund, landLeaseFee,
    rightFee, depositGuarantee, maintenanceFees, otherFees, bicycleParking,
    bikeStorage, siteArea, pets, landRights, managementForm, landLawNotification,
    currentSituation, extraditionPossibleDate, transactionMode, propertyNumber,
    informationReleaseDate, nextScheduledUpdateDate, remarks, evaluationCertificate,
    parking, kitchen, bathToilet, facilitiesServices, others, images
)
VALUES (
    'ブリリア門前仲町 20階 2LDK',
    158000000,
    2253521,
    '東京都江東区門前仲町1丁目4番8号',
    '2LDK',
    70.1,
    '地上35階建 / 20階',
    'RC',
    32600,
    '商業地域',
    '東京メトロ東西線 / 門前仲町駅 徒歩3分',
    ST_SetSRID(ST_MakePoint(139.7965, 35.6719), 4326),
    '中古マンション',
    '2022年6月',
    8.7,
    245,
    28900,
    22400,
    NULL,
    NULL,
    '管理費込み、インターネット使用料込み',
    NULL,
    '有',
    '有',
    NULL,
    '不可',
    '所有権',
    '全部委託／日勤',
    '届出不要',
    '空家',
    '即時',
    '専任媒介',
    1015229206,
    '2025-05-29',
    '2025-06-29',
    '門前仲町駅直結、高層階、東京スカイツリー眺望',
    NULL,
    '有',
    'カウンターキッチン',
    'バス・トイレ別',
    'ラウンジ、フィットネス、宅配ボックス、駐車場',
    'コンシェルジュ、24時間セキュリティ、クリーニング取次',
    ARRAY['/images/id26-1.jpg', '/images/id26-2.jpg', '/images/id26-3.jpg', '/images/id26-4.jpg', '/images/id26-5.jpg']
);
