INSERT INTO properties (
    title, price, pricePerSquareMeter, address, layout, area, floorInfo,
    structure, managementFee, areaOfUse, transportation, location, propertyType,
    yearBuilt, balconyArea, totalUnits, repairReserveFund, landLeaseFee,
    rightFee, depositGuarantee, maintenanceFees, otherFees, bicycleParking,
    bikeStorage, siteArea, pets, landRights, managementForm, landLawNotification,
    currentSituation, extraditionPossibleDate, transactionMode, propertyNumber,
    informationReleaseDate, nextScheduledUpdateDate, remarks, evaluationCertificate,
    parking, kitchen, bathToilet, facilitiesServices, others, images
)
VALUES (
    'ザ・パークハウス西新宿タワー60 45階 1LDK',
    195000000,
    3947368,
    '東京都新宿区西新宿5丁目5番1号',
    '1LDK',
    49.4,
    '地上60階建 / 45階',
    'SRC',
    35800,
    '商業地域',
    '東京メトロ丸ノ内線 / 西新宿駅 徒歩4分',
    ST_SetSRID(ST_MakePoint(139.6896, 35.6936), 4326),
    '中古マンション',
    '2023年3月',
    6.2,
    954,
    42500,
    35200,
    NULL,
    NULL,
    '管理費込み、修繕積立金別途',
    NULL,
    '有',
    '有',
    NULL,
    '不可',
    '所有権',
    '全部委託／日勤',
    '届出不要',
    '空家',
    '相談',
    '専任媒介',
    1015229207,
    '2025-05-29',
    '2025-06-29',
    '日本最高層級、富士山眺望、プレミアム仕様',
    NULL,
    '有',
    'アイランドキッチン',
    'バス・トイレ別',
    'スカイラウンジ、フィットネス、温浴施設、ゲストスイート',
    '24時間コンシェルジュ、ルームサービス、ランドリー',
    ARRAY['/images/id27-1.jpg', '/images/id27-2.jpg', '/images/id27-3.jpg', '/images/id27-4.jpg', '/images/id27-5.jpg']
);