INSERT INTO properties (
    title, price, pricePerSquareMeter, address, layout, area, floorInfo,
    structure, managementFee, areaOfUse, transportation, location, propertyType,
    yearBuilt, balconyArea, totalUnits, repairReserveFund, landLeaseFee,
    rightFee, depositGuarantee, maintenanceFees, otherFees, bicycleParking,
    bikeStorage, siteArea, pets, landRights, managementForm, landLawNotification,
    currentSituation, extraditionPossibleDate, transactionMode, propertyNumber,
    informationReleaseDate, nextScheduledUpdateDate, remarks, evaluationCertificate,
    parking, kitchen, bathToilet, facilitiesServices, others, images
)
VALUES (
    'ブリリア大井町ラヴィアンタワー 28階 3LDK',
    248000000,
    2574740,
    '東京都品川区大井1丁目47番1号',
    '3LDK',
    96.4,
    '地上40階建 / 28階',
    'RC',
    48900,
    '商業地域',
    'JR京浜東北線 / 大井町駅 徒歩5分',
    ST_SetSRID(ST_MakePoint(139.7305627311197,35.607608105896674), 4326),
    '中古マンション',
    '2019年11月',
    13.8,
    585,
    45200,
    38600,
    NULL,
    NULL,
    '管理費込み、修繕積立金別途',
    NULL,
    '有',
    '有',
    NULL,
    '可',
    '所有権',
    '全部委託／日勤',
    '届出不要',
    '居住中',
    '2025年10月',
    '専任媒介',
    1015229208,
    '2025-05-29',
    '2025-06-29',
    '大井町駅近、ファミリー向け、南向き眺望良好',
    NULL,
    '有',
    'システムキッチン',
    'バス・トイレ別',
    'キッズルーム、ラウンジ、ゲストルーム、宅配ボックス',
    'コンシェルジュ、24時間管理、クリーニング取次',
    ARRAY['/images/id28-1.jpg', '/images/id28-2.jpg', '/images/id28-3.jpg', '/images/id28-4.jpg', '/images/id28-5.jpg']
);