INSERT INTO properties (
    title, price, pricePerSquareMeter, address, layout, area, floorInfo,
    structure, managementFee, areaOfUse, transportation, location, propertyType,
    yearBuilt, balconyArea, totalUnits, repairReserveFund, landLeaseFee,
    rightFee, depositGuarantee, maintenanceFees, otherFees, bicycleParking,
    bikeStorage, siteArea, pets, landRights, managementForm, landLawNotification,
    currentSituation, extraditionPossibleDate, transactionMode, propertyNumber,
    informationReleaseDate, nextScheduledUpdateDate, remarks, evaluationCertificate,
    parking, kitchen, bathToilet, facilitiesServices, others, images
)
VALUES (
    'パークタワー晴海 32階 2SLDK',
    285000000,
    3846154,
    '東京都中央区晴海2丁目3番2号',
    '2SLDK',
    74.1,
    '地上52階建 / 32階',
    'SRC',
    38900,
    '準工業地域',
    '都営大江戸線 / 勝どき駅 徒歩8分',
    ST_SetSRID(ST_MakePoint(139.78815066123684,35.65730457830954), 4326),
    '中古マンション',
    '2024年1月',
    9.8,
    1418,
    52400,
    45800,
    NULL,
    NULL,
    '管理費込み、インターネット使用料込み',
    NULL,
    '有',
    '有',
    NULL,
    '相談',
    '所有権',
    '全部委託／日勤',
    '届出不要',
    '空家',
    '相談',
    '専任媒介',
    1015229209,
    '2025-05-29',
    '2025-06-29',
    '晴海最新タワー、東京湾眺望、レインボーブリッジビュー',
    NULL,
    '有',
    'カウンターキッチン',
    'バス・トイレ別',
    'スカイラウンジ、温浴施設、フィットネス、ゲストスイート',
    '24時間コンシェルジュ、ルームサービス、ハウスキーピング',
    ARRAY['/images/id29-1.jpg', '/images/id29-2.jpg', '/images/id29-3.jpg', '/images/id29-4.jpg', '/images/id29-5.jpg']
);