-- Sample property data
INSERT INTO properties (
    title, price, pricePerSquareMeter, address, layout, area, floorInfo, 
    structure, managementFee, areaOfUse, transportation, location, propertyType, 
    yearBuilt, balconyArea, totalUnits, repairReserveFund, landLeaseFee, 
    rightFee, depositGuarantee, maintenanceFees, otherFees, bicycleParking, 
    bikeStorage, siteArea, pets, landRights, managementForm, landLawNotification, 
    currentSituation, extraditionPossibleDate, transactionMode, propertyNumber, 
    informationReleaseDate, nextScheduledUpdateDate, remarks, evaluationCertificate, 
    parking, kitchen, bathToilet, facilitiesServices, others, images
)
VALUES (
    '東京ツインパークス　ライトウイング', 
    498000000, 
    3401100, 
    '東京都港区東新橋１丁目', 
    '2LDK', 
    99.10, 
    '42/47階', 
    'RC', 
    36700, 
    '準工業地域', 
    '東京都大江戸線 「汐留」駅 まで 徒歩3分 山手線 「浜松町」駅 まで 徒歩7分', 
    ST_SetSRID(ST_MakePoint(139.76024876736125, 35.66059974713901), 4326), -- Single Point: [lng, lat]
    '中古マンション', 
    '2002年9月', 
    6.28, 
    424, 
    30620, 
    8455, 
    NULL, 
    NULL, 
    'インターネット接続料: 2,200円/月、自治会費: 150円/月', 
    NULL, 
    '有', 
    '有', 
    NULL, 
    '相談', 
    '所有権', 
    '全部委託／日勤', 
    '届出不要', 
    '居住中', 
    '相談', 
    '専任媒介', 
    1015229195, 
    '2025-05-29', 
    '2025-06-05', 
    '主要採光面：北向き, 施工会社：（株）大林組, 用途地域：準工業', 
    '長期優良住宅認定通知書, 長期優良住宅認定通知書あり', 
    '空無', 
    'カウンターキッチン', 
    '-', 
    '全居室収納、ウォークインクローゼット、床暖房、トランクルーム、オートロック、モニター付インターホン、ディンプルキー、防犯カメラ、都市ガス、ケーブルTV', 
    '日勤管理 ・掲載中の家具・什器は販売価格に含まれません', 
    ARRAY['/images/id3-1.jpg', '/images/id3-2.jpg', '/images/id3-3.jpg', '/images/id3-4.jpg', '/images/id3-5.jpg']
);