-- Sample property data
INSERT INTO properties (
    title, price, pricePerSquareMeter, address, layout, area, floorInfo, 
    structure, managementFee, areaOfUse, transportation, location, propertyType, 
    yearBuilt, balconyArea, totalUnits, repairReserveFund, landLeaseFee, 
    rightFee, depositGuarantee, maintenanceFees, otherFees, bicycleParking, 
    bikeStorage, siteArea, pets, landRights, managementForm, landLawNotification, 
    currentSituation, extraditionPossibleDate, transactionMode, propertyNumber, 
    informationReleaseDate, nextScheduledUpdateDate, remarks, evaluationCertificate, 
    parking, kitchen, bathToilet, facilitiesServices, others, images
)
VALUES (
    '六本木ヒルズレジデンスB棟', 
    492000000, 
    3401100, 
    '東京都港区六本木６丁目', 
    '2LDK', 
    89.59, 
    '5/43階', 
    'RC', 
    72650, 
    '準工業地域', 
    '東京地下鉄日比谷線 「六本木」駅 まで 徒歩6分 東京都大江戸線 「麻布十番」駅 まで 徒歩10分', 
    ST_SetSRID(ST_MakePoint(139.72957203298222, 35.659029582092316), 4326), -- Single Point: [lng, lat]
    '中古マンション', 
    '2003年4月', 
    5.19, 
    333, 
    40082, 
    NULL, 
    NULL, 
    NULL, 
    'インターネット接続料: 2,200円/月、自治会費: 150円/月', 
    NULL, 
    '有', 
    '有', 
    NULL, 
    '相談', 
    '所有権', 
    '全部委託／日勤', 
    '届出不要', 
    '賃貸中', 
    '相談', 
    '専任媒介', 
    1015229195, 
    '2025-05-29', 
    '2025-06-05', 
    '主要採光面：北向き, 施工会社：（株）大林組, 用途地域：準工業', 
    '長期優良住宅認定通知書, 長期優良住宅認定通知書あり', 
    '空無', 
    'カウンターキッチン', 
    '-', 
    '全居室収納、ウォークインクローゼット、床暖房、トランクルーム、オートロック、モニター付インターホン、ディンプルキー、防犯カメラ、都市ガス、ケーブルTV', 
    '共有持分：46560／100000000・バルコニー面積は平面図上で測定した面積であり、おおよその表示です。 駐車場空状況：2025年4月確認 565000円', 
    ARRAY['/images/id4-1.jpg', '/images/id4-2.jpg', '/images/id4-3.jpg', '/images/id4-4.jpg', '/images/id4-5.jpg']
);