INSERT INTO properties (
    title, price, pricePerSquareMeter, address, layout, area, floorInfo,
    structure, managementFee, areaOfUse, transportation, location, propertyType,
    yearBuilt, balconyArea, totalUnits, repairReserveFund, landLeaseFee,
    rightFee, depositGuarantee, maintenanceFees, otherFees, bicycleParking,
    bikeStorage, siteArea, pets, landRights, managementForm, landLawNotification,
    currentSituation, extraditionPossibleDate, transactionMode, propertyNumber,
    informationReleaseDate, nextScheduledUpdateDate, remarks, evaluationCertificate,
    parking, kitchen, bathToilet, facilitiesServices, others, images
)
VALUES (
    'シティタワーズ豊洲　ザ・ツイン　ノースタワー 48階 ２ＬＤＫ',
    398000000,
    2999500,
    '東京都江東区豊洲３丁目',
    '2LDK',
    132.69,
    '地上48階地下1階建 / 48階',
    'RC',
    21240,
    '準工業地域',
    '東京メトロ有楽町線 / 豊洲駅 徒歩4分, 新交通ゆりかもめ / 新豊洲駅 徒歩18分',
    ST_SetSRID(ST_MakePoint(139.79902357670514,35.65775190277236), 4326),
    '中古マンション',
    '2009年2月',
    22.38,
    1418,
    40460,
    NULL,
    NULL,
    NULL,
    '管理費込み、インターネット使用料込み',
    NULL,
    '有',
    '有',
    NULL,
    '相談',
    '所有権',
    '全部委託／日勤',
    '届出不要',
    '賃貸中',
    '相談',
    '専任媒介',
    1122083505,
    '2025-02-22',
    '2025-06-09',
    '主要採光面：西向き,施工会社：鹿島建設（株）, 用途地域：工業地域, 利回り：2.11%, 年間予定賃料収入：839.78万円ノース棟・サウス棟からなる166ｍのツインタワーは豊洲のタワーマンション',
    NULL,
    '有',
    'カウンターキッチン',
    'バス・トイレ別',
    'スカイラウンジ、温浴施設、フィットネス、ゲストスイート',
    '24時間コンシェルジュ、ルームサービス、ハウスキーピング',
    ARRAY['/images/id40-1.jpg', '/images/id40-2.jpg', '/images/id40-3.jpg', '/images/id40-4.jpg', '/images/id40-5.jpg']
);