INSERT INTO properties (
    title, price, pricePerSquareMeter, address, layout, area, floorInfo,
    structure, managementFee, areaOfUse, transportation, location, propertyType,
    yearBuilt, balconyArea, totalUnits, repairReserveFund, landLeaseFee,
    rightFee, depositGuarantee, maintenanceFees, otherFees, bicycleParking,
    bikeStorage, siteArea, pets, landRights, managementForm, landLawNotification,
    currentSituation, extraditionPossibleDate, transactionMode, propertyNumber,
    informationReleaseDate, nextScheduledUpdateDate, remarks, evaluationCertificate,
    parking, kitchen, bathToilet, facilitiesServices, others, images
)
VALUES (
    'シティタワーズ豊洲ザ・ツイン サウスタワー',
    199000000,
    2999500,
    '東京都江東区豊洲３丁目',
    '3LDK',
    86.65,
    '24階 / 地上48階 地下1階建',
    'RC',
    21440,
    '準工業地域',
    '東京メトロ有楽町線 豊洲駅 徒歩4分, ゆりかもめ 豊洲駅 徒歩6分',
    ST_SetSRID(ST_MakePoint(139.79902357670514,35.65775190277236), 4326),
    '中古マンション',
    '2009年2月',
    5.21,
    602,
    27140,
    NULL,
    NULL,
    NULL,
    '管理費込み、インターネット使用料込み',
    NULL,
    '有',
    '有',
    NULL,
    '相談',
    '所有権',
    '全部委託／日勤',
    '届出不要',
    '居住中',
    '相談',
    '仲介',
    1122083505,
    '2025-05-29',
    '2025-06-12',
    '主要採光面：東向き,住友不動産建物サービス（株）',
    NULL,
    '有',
    'カウンターキッチン',
    'バス・トイレ別',
    'スカイラウンジ、温浴施設、フィットネス、ゲストスイート',
    '24時間コンシェルジュ、ルームサービス、ハウスキーピング',
    ARRAY['/images/id41-1.jpg', '/images/id41-2.jpg', '/images/id41-3.jpg', '/images/id41-4.jpg', '/images/id41-5.jpg']
);