INSERT INTO properties (
    title, price, pricePerSquareMeter, address, layout, area, floorInfo,
    structure, managementFee, areaOfUse, transportation, location, propertyType,
    yearBuilt, balconyArea, totalUnits, repairReserveFund, landLeaseFee,
    rightFee, depositGuarantee, maintenanceFees, otherFees, bicycleParking,
    bikeStorage, siteArea, pets, landRights, managementForm, landLawNotification,
    currentSituation, extraditionPossibleDate, transactionMode, propertyNumber,
    informationReleaseDate, nextScheduledUpdateDate, remarks, evaluationCertificate,
    parking, kitchen, bathToilet, facilitiesServices, others, images
)
VALUES (
    'ライオンズミレス蔵前',
    6280000,
    2999500,
    '東京都台東区駒形１丁目',
    '1LDK',
    35.6,
    '4階 / 地上15階建',
    'RC',
    13400,
    '準工業地域',
    '都営大江戸線 蔵前駅 徒歩2分, 都営浅草線 蔵前駅 徒歩4分',
    ST_SetSRID(ST_MakePoint(139.7931122454882, 35.705801994104405), 4326),
    '中古マンション',
    '2023年01月築',
    3.00,
    602,
    5200,
    NULL,
    NULL,
    NULL,
    '管理費込み、インターネット使用料込み',
    NULL,
    '有',
    '有',
    NULL,
    '相談',
    '所有権',
    '全部委託／日勤',
    '届出不要',
    '居住中',
    '相談',
    '仲介',
    1122083505,
    '2025-05-26',
    '2025-06-09',
    '主要採光面：東向き,住友不動産建物サービス（株）',
    NULL,
    '有',
    'カウンターキッチン',
    'バス・トイレ別',
    'スカイラウンジ、温浴施設、フィットネス、ゲストスイート',
    '24時間コンシェルジュ、ルームサービス、ハウスキーピング',
    ARRAY['/images/id42-1.jpg', '/images/id42-2.jpg', '/images/id42-3.jpg', '/images/id42-4.jpg', '/images/id42-5.jpg']
);