INSERT INTO properties (
    title, price, pricePerSquareMeter, address, layout, area, floorInfo,
    structure, managementFee, areaOfUse, transportation, location, propertyType,
    yearBuilt, balconyArea, totalUnits, repairReserveFund, landLeaseFee,
    rightFee, depositGuarantee, maintenanceFees, otherFees, bicycleParking,
    bikeStorage, siteArea, pets, landRights, managementForm, landLawNotification,
    currentSituation, extraditionPossibleDate, transactionMode, propertyNumber,
    informationReleaseDate, nextScheduledUpdateDate, remarks, evaluationCertificate,
    parking, kitchen, bathToilet, facilitiesServices, others, images
)
VALUES (
    'クレアホームズフラン東京三ノ輪Ⅱ',
    50000000,
    2999500,
    '東京都台東区三ノ輪１丁目',
    '1LDK',
    32.78,
    '3階 / 地上12階建',
    'RC',
    14400,
    '準工業地域',
    '東京メトロ日比谷線 三ノ輪駅 徒歩4分, 常磐線 南千住駅 徒歩12分, つくばエクスプレス 南千住駅 徒歩12分',
    ST_SetSRID(ST_MakePoint(139.79401790614241, 35.7281325127099), 4326),
    '中古マンション',
    '2023年07月',
    5.6,
    33,
    2950,
    NULL,
    NULL,
    NULL,
    '管理費込み、インターネット使用料込み',
    NULL,
    '有',
    '有',
    NULL,
    '相談',
    '所有権',
    '全部委託／日勤',
    '届出不要',
    '賃貸中',
    '相談',
    '仲介',
    1122083505,
    '2025-05-26',
    '2025-06-12',
    '主要採光面：東向き,住友不動産建物サービス（株）',
    NULL,
    '有',
    'カウンターキッチン',
    'バス・トイレ別',
    'スカイラウンジ、温浴施設、フィットネス、ゲストスイート',
    '24時間コンシェルジュ、ルームサービス、ハウスキーピング',
    ARRAY['/images/id43-1.jpg', '/images/id43-2.jpg', '/images/id43-3.jpg', '/images/id43-4.jpg', '/images/id43-5.jpg']
);