INSERT INTO properties (
    title, price, pricePerSquareMeter, address, layout, area, floorInfo,
    structure, managementFee, areaOfUse, transportation, location, propertyType,
    yearBuilt, balconyArea, totalUnits, repairReserveFund, landLeaseFee,
    rightFee, depositGuarantee, maintenanceFees, otherFees, bicycleParking,
    bikeStorage, siteArea, pets, landRights, managementForm, landLawNotification,
    currentSituation, extraditionPossibleDate, transactionMode, propertyNumber,
    informationReleaseDate, nextScheduledUpdateDate, remarks, evaluationCertificate,
    parking, kitchen, bathToilet, facilitiesServices, others, images
)
VALUES (
    'リビオレゾン上野入谷ザ・テラス',
    44990000,
    2999500,
    '東京都台東区入谷２丁目',
    '1LDK',
    32.02,
    '14階 / 地上15階建',
    'RC',
    8860,
    '準工業地域',
    '東京メトロ日比谷線 入谷駅 徒歩6分, 山手線 鶯谷駅 徒歩13分, つくばエクスプレス 浅草駅 徒歩11分',
    ST_SetSRID(ST_MakePoint(139.7881313558237, 35.718988908509424), 4326),
    '中古マンション',
    '2021年08月築',
    3.61,
    98,
    2560,
    NULL,
    NULL,
    NULL,
    '管理費込み、インターネット使用料込み',
    NULL,
    '有',
    '有',
    NULL,
    '相談',
    '所有権',
    '全部委託／日勤',
    '届出不要',
    '居住中',
    '相談',
    '仲介',
    1122083505,
    '2025-06-01',
    '2025-06-15',
    '主要採光面：東向き,住友不動産建物サービス（株）',
    NULL,
    '有',
    'カウンターキッチン',
    'バス・トイレ別',
    'スカイラウンジ、温浴施設、フィットネス、ゲストスイート',
    '24時間コンシェルジュ、ルームサービス、ハウスキーピング',
    ARRAY['/images/id44-1.jpg', '/images/id44-2.jpg', '/images/id44-3.jpg', '/images/id44-4.jpg', '/images/id44-5.jpg']
);