INSERT INTO properties (
    title, price, pricePerSquareMeter, address, layout, area, floorInfo,
    structure, managementFee, areaOfUse, transportation, location, propertyType,
    yearBuilt, balconyArea, totalUnits, repairReserveFund, landLeaseFee,
    rightFee, depositGuarantee, maintenanceFees, otherFees, bicycleParking,
    bikeStorage, siteArea, pets, landRights, managementForm, landLawNotification,
    currentSituation, extraditionPossibleDate, transactionMode, propertyNumber,
    informationReleaseDate, nextScheduledUpdateDate, remarks, evaluationCertificate,
    parking, kitchen, bathToilet, facilitiesServices, others, images
)
VALUES (
    'ルフォン根岸三丁目',
    98000000,
    2999500,
    '東京都台東区根岸３丁目',
    '3LDK',
    66.84,
    '7階 / 地上15階建',
    'RC',
    12500,
    '準工業地域',
    '山手線 鶯谷駅 徒歩5分, 東京メトロ日比谷線 入谷駅 徒歩4分, 山手線 上野駅 徒歩12分',
    ST_SetSRID(ST_MakePoint(139.78198596080233, 35.72201435727541), 4326),
    '中古マンション',
    '2016年09月築',
    12,
    98,
    11370,
    NULL,
    NULL,
    NULL,
    '管理費込み、インターネット使用料込み',
    NULL,
    '有',
    '有',
    NULL,
    '相談',
    '所有権',
    '全部委託／日勤',
    '届出不要',
    '居住中',
    '相談',
    '仲介',
    1122083505,
    '2025-05-22',
    '2025-06-05',
    '主要採光面：東向き,住友不動産建物サービス（株）',
    NULL,
    '有',
    'カウンターキッチン',
    'バス・トイレ別',
    'スカイラウンジ、温浴施設、フィットネス、ゲストスイート',
    '24時間コンシェルジュ、ルームサービス、ハウスキーピング',
    ARRAY['/images/id45-1.jpg', '/images/id45-2.jpg', '/images/id45-3.jpg', '/images/id45-4.jpg', '/images/id45-5.jpg']
);