-- Sample property data
INSERT INTO properties (
    title, price, pricePerSquareMeter, address, layout, area, floorInfo, 
    structure, managementFee, areaOfUse, transportation, location, propertyType, 
    yearBuilt, balconyArea, totalUnits, repairReserveFund, landLeaseFee, 
    rightFee, depositGuarantee, maintenanceFees, otherFees, bicycleParking, 
    bikeStorage, siteArea, pets, landRights, managementForm, landLawNotification, 
    currentSituation, extraditionPossibleDate, transactionMode, propertyNumber, 
    informationReleaseDate, nextScheduledUpdateDate, remarks, evaluationCertificate, 
    parking, kitchen, bathToilet, facilitiesServices, others, images
)
VALUES (
    'パークコート麻布十番ザ・タワー', 
    428000000, 
    3401100, 
    '東京都港区三田１丁目', 
    '3LDK', 
    89.69, 
    '27/36階', 
    'RC', 
    32440, 
    '準工業地域', 
    '東京地下鉄南北線 「麻布十番」駅 まで 徒歩3分 東京都大江戸線 「麻布十番」駅 まで 徒歩3分', 
    ST_SetSRID(ST_MakePoint(139.73985472133614,35.65463430793352), 4326), -- Single Point: [lng, lat]
    '中古マンション', 
    '2010年5月', 
    8.04, 
    440, 
    18360, 
    NULL, 
    NULL, 
    NULL, 
    'インターネット接続料: 2,200円/月、自治会費: 150円/月', 
    NULL, 
    '有', 
    '有', 
    NULL, 
    '相談', 
    '所有権', 
    '全部委託／日勤', 
    '届出不要', 
    '居住中', 
    '相談', 
    '専任媒介', 
    1015229195, 
    '2025-05-29', 
    '2025-06-05', 
    '主要採光面：北向き, 施工会社：（株）大林組, 用途地域：準工業', 
    '長期優良住宅認定通知書, 長期優良住宅認定通知書あり', 
    '空無', 
    'カウンターキッチン', 
    '-', 
    '全居室収納、ウォークインクローゼット、床暖房、トランクルーム、オートロック、モニター付インターホン、ディンプルキー、防犯カメラ、都市ガス、ケーブルTV', 
    '駐輪場使用料：月額300円　　・バイク置き場使用料：月額2，000-3，000円／用途地域2：第二種住居地域', 
    ARRAY['/images/id5-1.jpg', '/images/id5-2.jpg', '/images/id5-3.jpg', '/images/id5-4.jpg', '/images/id5-5.jpg']
);