-- Sample property data
INSERT INTO properties (
    title, price, pricePerSquareMeter, address, layout, area, floorInfo, 
    structure, managementFee, areaOfUse, transportation, location, propertyType, 
    yearBuilt, balconyArea, totalUnits, repairReserveFund, landLeaseFee, 
    rightFee, depositGuarantee, maintenanceFees, otherFees, bicycleParking, 
    bikeStorage, siteArea, pets, landRights, managementForm, landLawNotification, 
    currentSituation, extraditionPossibleDate, transactionMode, propertyNumber, 
    informationReleaseDate, nextScheduledUpdateDate, remarks, evaluationCertificate, 
    parking, kitchen, bathToilet, facilitiesServices, others, images
)
VALUES (
    'ＴＨＥ　ＲＯＰＰＯＮＧＩ　ＴＯＫＹＯ', 
    529900000, 
    3401100, 
    '東京都港区六本木３丁目', 
    '2LDK', 
    104.40, 
    '37/39階', 
    'RC', 
    43210, 
    '準工業地域', 
    '東京地下鉄日比谷線 「六本木」駅 まで 徒歩3分 東京地下鉄南北線 「六本木一丁目」駅 まで 徒歩6分', 
    ST_SetSRID(ST_MakePoint(139.735074, 35.66447297370981), 4326), -- Single Point: [lng, lat]
    '中古マンション', 
    '2011年11月', 
    8.04, 
    611, 
    11320, 
    NULL, 
    NULL, 
    NULL, 
    'インターネット接続料: 2,200円/月、自治会費: 150円/月', 
    NULL, 
    '有', 
    '有', 
    NULL, 
    'ペット可', 
    '所有権', 
    '全部委託／日勤', 
    '届出不要', 
    '空家', 
    '相談', 
    '専任媒介', 
    1015229195, 
    '2025-05-29', 
    '2025-06-05', 
    '主要採光面：北向き', 
    '長期優良住宅認定通知書, 長期優良住宅認定通知書あり', 
    '空無', 
    'カウンターキッチン', 
    '-', 
    'オール電化／電気温水器', 
    '※家具・調度品等は販売価格に含まれておりません。', 
    ARRAY['/images/id6-1.jpg', '/images/id6-2.jpg', '/images/id6-3.jpg', '/images/id6-4.jpg', '/images/id6-5.jpg']
);