-- Sample property data
INSERT INTO properties (
    title, price, pricePerSquareMeter, address, layout, area, floorInfo, 
    structure, managementFee, areaOfUse, transportation, location, propertyType, 
    yearBuilt, balconyArea, totalUnits, repairReserveFund, landLeaseFee, 
    rightFee, depositGuarantee, maintenanceFees, otherFees, bicycleParking, 
    bikeStorage, siteArea, pets, landRights, managementForm, landLawNotification, 
    currentSituation, extraditionPossibleDate, transactionMode, propertyNumber, 
    informationReleaseDate, nextScheduledUpdateDate, remarks, evaluationCertificate, 
    parking, kitchen, bathToilet, facilitiesServices, others, images,
    -- New hierarchical area fields and zipcode
    zipcode, area_level_1, area_level_2, area_level_3, area_level_4, status     
)
VALUES (
    'Ｂｒｉｌｌｉａ銀座ｉｄ', 
    64990000, 
    3401100, 
    '東京都中央区銀座２丁目', 
    '1K', 
    26.73, 
    '14階 / 地上14階建', 
    'RC', 
    9100, 
    '準工業地域', 
    '東京都浅草線 「東銀座」駅 まで 徒歩3分 東京地下鉄銀座線 「銀座」駅 まで 徒歩6分', 
    ST_SetSRID(ST_MakePoint(139.7716951057149, 35.67004812969985), 4326), -- Single Point: [lng, lat]
    '中古マンション', 
    '2004年10月', 
    5.95, 
    160, 
    1980, 
    NULL, 
    NULL, 
    NULL, 
    'インターネット接続料: 2,200円/月、自治会費: 150円/月', 
    NULL, 
    '有', 
    '有', 
    NULL, 
    'ペット可', 
    '所有権', 
    '全部委託／日勤', 
    '届出不要', 
    '居住中', 
    '相談', 
    '専任媒介', 
    1015229195, 
    '2025-05-29', 
    '2025-06-05', 
    '主要採光面：北向き', 
    '長期優良住宅認定通知書, 長期優良住宅認定通知書あり', 
    '空無', 
    'カウンターキッチン', 
    '-', 
    'オール電化／電気温水器', 
    '※上記壁芯面積はトランクルーム面積（約０．２８平米）を含みます', 
    ARRAY['/images/id7-1.jpg', '/images/id7-2.jpg', '/images/id7-3.jpg', '/images/id7-4.jpg', '/images/id7-5.jpg'],
    '104-0051',
    '首都圏',
    '東京都',
    '23区',
    '中央区',
    'for sale' -- Property status     
);