-- Sample property data
INSERT INTO properties (
    title, price, pricePerSquareMeter, address, layout, area, floorInfo, 
    structure, managementFee, areaOfUse, transportation, location, propertyType, 
    yearBuilt, balconyArea, totalUnits, repairReserveFund, landLeaseFee, 
    rightFee, depositGuarantee, maintenanceFees, otherFees, bicycleParking, 
    bikeStorage, siteArea, pets, landRights, managementForm, landLawNotification, 
    currentSituation, extraditionPossibleDate, transactionMode, propertyNumber, 
    informationReleaseDate, nextScheduledUpdateDate, remarks, evaluationCertificate, 
    parking, kitchen, bathToilet, facilitiesServices, others, images,
    -- New hierarchical area fields and zipcode
    zipcode, area_level_1, area_level_2, area_level_3, area_level_4, status     
)
VALUES (
    'ＨＡＲＵＭＩ　ＦＬＡＧ　ＳＵＮ　ＶＩＬＬＡＧＥＦ棟', 
    197000000, 
    3401100, 
    '東京都中央区晴海５丁目', 
    '3LDK', 
    86.45, 
    '13階 / 地上18階建', 
    'RC', 
    26280, 
    '準工業地域', 
    '東京都大江戸線 「勝どき」駅 まで 徒歩17分', 
    ST_SetSRID(ST_MakePoint(139.77309119865183,35.65011062484388), 4326), -- Single Point: [lng, lat]
    '中古マンション', 
    '2023年11月', 
    21.35, 
    194, 
    12620, 
    3350, 
    NULL, 
    NULL, 
    'インターネット接続料: 2,200円/月、自治会費: 150円/月', 
    NULL, 
    '有', 
    '有', 
    NULL, 
    'ペット可', 
    '所有権', 
    '全部委託／日勤', 
    '届出不要', 
    '居住中', 
    '相談', 
    '専任媒介', 
    1015229195, 
    '2025-05-29', 
    '2025-06-05', 
    '主要採光面：北向き', 
    'インターネット料、自治会費、HARUMI FLAG CLUB会費', 
    '空無', 
    'カウンターキッチン', 
    '-', 
    'オール電化／電気温水器', 
    '日勤管理 掲載中の家具・什器および内装費用等は販売価格に含まれません', 
    ARRAY['/images/id8-1.jpg', '/images/id8-2.jpg', '/images/id8-3.jpg', '/images/id8-4.jpg', '/images/id8-5.jpg'],
    '104-0051',
    '首都圏',
    '東京都',
    '23区',
    '中央区',
    'for sale' -- Property status      
);