-- Sample property data
INSERT INTO properties (
    title, price, pricePerSquareMeter, address, layout, area, floorInfo, 
    structure, managementFee, areaOfUse, transportation, location, propertyType, 
    yearBuilt, balconyArea, totalUnits, repairReserveFund, landLeaseFee, 
    rightFee, depositGuarantee, maintenanceFees, otherFees, bicycleParking, 
    bikeStorage, siteArea, pets, landRights, managementForm, landLawNotification, 
    currentSituation, extraditionPossibleDate, transactionMode, propertyNumber, 
    informationReleaseDate, nextScheduledUpdateDate, remarks, evaluationCertificate, 
    parking, kitchen, bathToilet, facilitiesServices, others, images,
    -- New hierarchical area fields and zipcode
    zipcode, area_level_1, area_level_2, area_level_3, area_level_4, status      
)
VALUES (
    '白金ザ・スカイ　西棟', 
    222000000, 
    3401100, 
    '東京都港区白金１丁目', 
    '2LDK', 
    55.88, 
    '14階 / 地上45階建', 
    'RC', 
    21592, 
    '準工業地域', 
    '東京地下鉄南北線 「白金高輪」駅 まで 徒歩3分 東京都三田線 「白金高輪」駅 まで 徒歩3分', 
    ST_SetSRID(ST_MakePoint(139.73416295627342,35.64640510689863), 4326), -- Single Point: [lng, lat]
    '中古マンション', 
    '2023年2月', 
    6.20, 
    1247, 
    7210, 
    NULL, 
    NULL, 
    NULL, 
    'インターネット接続料: 2,200円/月、自治会費: 150円/月', 
    NULL, 
    '有', 
    '有', 
    NULL, 
    'ペット可', 
    '所有権', 
    '全部委託／日勤', 
    '届出不要', 
    '居住中', 
    '相談', 
    '専任媒介', 
    1015229195, 
    '2025-05-29', 
    '2025-06-05', 
    '主要採光面：北向き', 
    'インターネット料、自治会費、HARUMI FLAG CLUB会費', 
    '空無', 
    'カウンターキッチン', 
    '-', 
    'オール電化／電気温水器', 
    '※総戸数：１２４７戸※記載内容と現況が異なる場合は現況を優先とさせていただきます。※専有面積にはトランクルーム面積０．６４平米を含みます。', 
    ARRAY['/images/id9-1.jpg', '/images/id9-2.jpg', '/images/id9-3.jpg', '/images/id9-4.jpg', '/images/id9-5.jpg'],
    '105-0021',
    '首都圏',
    '東京都',
    '23区',
    '港区',
    'for sale' -- Property status   
);