// src/utils/japanesePhrases.js

const japanesePhrases = {
    // Navigation
    appTitle: '不動産ファインダー',
    buy: '購入',
    rent: '賃貸',
    sell: '売却',
    agents: '不動産会社',
    signIn: 'ログイン',
    advertisement: '広告',
    help: 'ヘルプ',

    // Filters
    findYourPerfectHome: '理想の住まいを探す',
    location: 'エリア',
    locationPlaceholder: 'エリアを入力',
    propertyType: '物件種別',
    any: 'すべて',
    house: '戸建',
    apartment: 'マンション',
    mansion: '高級マンション',
    land: '土地',
    priceRange: '価格帯',
    min: '下限',
    max: '上限',
    layout: '間取り',
    structure: '建物構造',
    squareFeet: '面積（㎡）',
    yearBuilt: '築年月',
    managementFee: '管理費',
    features: '設備・特徴',
    garage: '駐車場',
    ac: 'エアコン',
    autoLock: 'オートロック',
    search: '検索する',
    filters: '絞り込み条件',
    oldApartment: "中古マンション",

    // Property details
    propertyDetails: '物件詳細',
    viewFullscreen: '写真をクリックすると全画面で表示されます',
    photos: '写真',
    failedToLoad: 'ロードに失敗しました',
    noImagesAvailable: '利用可能な画像がありません',
    bed: '部屋',
    beds: '部屋',
    sqft: '㎡',
    areaOfUse: '用途地域',
    transportation: '交通',
    propertyInfo: '物件情報',
    address: '所在地',
    price: '価格',
    priceAndFees: '価格と手数料',
    pricePerSquareMeter: '平米単価',
    repairReserveFund: '修繕積立金',
    floorInfo: '階数 / 階建',
    area: '専有面積',
    loanCalculator: 'ローンシミュレーター',
    contactAgent: 'お問い合わせ',
    balcony: "バルコニー",
    landLeaseFee: "借地期間",
    rightFee: "権利金",
    depositGuarantee: "敷金 / 保証金",
    maintenanceFees: "維持費等",
    otherFees: "その他費用",
    totalUnits: "総戸数",
    parking: "駐車場",
    bikeStorage: "バイク置き場",
    bicycleParking: "駐輪場",
    pets: "ペット",
    landRights: "土地権利",
    siteArea: "敷地面積",
    managementForm: "管理形態",
    landLawNotofication: "国土法届出",
    currentSituation: "現況",
    extraditionPossibleDate: "引渡可能時期",
    transactionMode: "取引態様",
    propertyNumber: "物件番号",
    informationReleaseDate: "情報公開日",
    nextScheduledUpdateDate: "次回更新予定日",
    kitchen: "キッチン",
    bathToilet: "バス・トイレ",
    facilitiesServices: "設備・サービス",
    others: "その他",
    direction: '向き',
    remarks: '備考',
    urbanPlanning: '都市計画',
    condominiumSalesCompany: '分譲会社',
    constructionCompany: '施工会社',
    designCompany: '設計会社',
    managementCompany: '管理会社',
    oneBuildingApartment: '一棟アパート',    

    //below is for house
    buildingArea: '建物面積',
    landArea: '土地面積',
    accessSituation: '接道状況',
    buildingCoverageRatio: '建ぺい率',
    floorAreaRatio: '容積率',

    //below is for 一棟アパート
    estimatedRent: '想定賃料(年間)',
    assumedYield: '想定利回り',
    currentRent: '現行賃料(年間)',
    currentyield: '現行利回り',
    rentalStatus: '賃貸状況',
    numberOfUnitsInTheBuilding: '建物内の住戸数',
    exclusiveAreaOfEachResidence: '各住戸の専有面積',

    // Status messages
    loading: '読み込み中...',
    errorLoading: 'データの読み込みに失敗しました',
    retry: '再試行',
    noProperties: '条件に合う物件がありません',
    tryAdjusting: '検索条件を変更してお試しください',

    // Property popup
    viewDetails: '詳細を見る',
    close: '閉じる',

    // Form fields
    submit: '送信',
    cancel: 'キャンセル',

    // Property types
    usedApartment: '中古マンション',
    newApartment: '新築マンション',
    usedHouse: '中古一戸建て',
    newHouse: '新築一戸建て',

    // Login/Register
    welcome: "不動産ファインダーへようこそ",
    signIn: "ログイン",
    newAccount: "新規登録",
    fullName: "お名前",
    fullNamePlaceholder: "お名前を入力してください",
    email: "メールアドレス",
    emailPlaceholder: "メールアドレスを入力してください",
    password: "パスワード",
    passwordPlaceholder: "パスワードを入力してください",
    createPasswordPlaceholder: "新しいパスワードを作成してください",
    confirmPassword: "パスワード（確認）",
    confirmPasswordPlaceholder: "パスワードを再入力してください",
    forgotPassword: "パスワードをお忘れですか？",
    createAccount: "アカウント作成",
    orConnectWith: "または以下でログイン",
    continueWithGoogle: "Googleでログイン",
    continueWithLine: "LINEでログイン",
    continueWithYahoo: "Yahoo!でログイン",

    // 東京23区
    chiyodaWard: '千代田区',
    chuoWard: '中央区',
    minatoWard: '港区',
    shinjukuWard: '新宿区',
    bunkyoWard: '文京区',
    taitoWard: '台東区',
    sumidaWard: '墨田区',
    kotoWard: '江東区',
    shinagawaWard: '品川区',
    meguroWard: '目黒区',
    OtaWard: '大田区',
    setagayaWard: '世田谷区',
    shibuyaWard: '渋谷区',
    nakanoWard: '中野区',
    suginamiWard: '杉並区',
    toshimaWard: '豊島区',
    kitaWard: '北区',
    arakawaWard: '荒川区',
    itabashiWard: '板橋区',
    nerimaWard: '練馬区',
    adachiWard: '足立区',
    katsushikaWard: '葛飾区',
    edogawaWard: '江戸川区',


    // Other common terms
    yes: 'はい',
    no: 'いいえ',
    back: '戻る',
    next: '次へ',
    save: '保存',
    delete: '削除',
    edit: '編集'



};

export default japanesePhrases;