-- Sample property data
INSERT INTO properties (
    title, price, price_per_square_meter, address, layout, area, floor_info, 
    structure, management_fee, area_of_use, transportation, location, property_type, 
    year_built, balcony_area, total_units, repair_reserve_fund, land_lease_fee, 
    right_fee, deposit_guarantee, maintenance_fees, other_fees, bicycle_parking, 
    bike_storage, site_area, pets, land_rights, management_form, land_law_notification, 
    current_situation, extradition_possible_date, transaction_mode, property_number, 
    information_release_date, next_scheduled_update_date, remarks, evaluation_certificate, 
    parking, kitchen, bath_toilet, facilities_services, others, images
)
VALUES (
    'ザ・パークハウス晴海タワーズ クロノレジデンス', 
    139800000, 
    1899973, 
    '東京都中央区晴海２丁目', 
    '3LDK', 
    73.58, 
    '地上49階・地下2階建 29階部分', 
    'RC', 
    22050, 
    '準工業地域', 
    '東京都大江戸線 「勝どき」駅 徒歩12分, 東京都大江戸線 「月島」駅 徒歩15分, 東京地下鉄有楽町線 「月島」駅 徒歩15分', 
    point(35.656645, 139.787052), 
    '中古マンション', 
    '2013年11月', 
    11.27, 
    883, 
    7860, 
    0, 
    0, 
    0, 
    'インターネット接続料: 2,200円/月、自治会費: 150円/月', 
    0, 
    '有', 
    '有', 
    '-', 
    '相談', 
    '所有権', 
    '全部委託／日勤', 
    '届出不要', 
    '空家', 
    '相談', 
    '専任媒介', 
    1011352391, 
    '2025-04-04', 
    '2025-05-19', 
    '主要採光面：北向き, 施工会社：（株）大林組, 用途地域：準工業', 
    '長期優良住宅認定通知書, 長期優良住宅認定通知書あり', 
    '空無', 
    'カウンターキッチン', 
    '-', 
    '全居室収納、ウォークインクローゼット、収納スペース、室内洗濯機置場、シューズインクローゼット、都市ガス', 
    'ペット用施設、キッズルーム、フィットネス施設、共用パーティルーム、エレベーター', 
    ARRAY['/images/id1-1.jpg', '/images/id1-2.jpg', '/images/id1-3.jpg', '/images/id1-4.jpg', '/images/id1-5.jpg']
);